import type { DealRoom } from "./schemas";

export const MOCK_DEAL_ROOM: DealRoom = {
  dealId: "deal_demo_001",
  slug: "demo",
  companyName: "Atlas Robotics",
  companyDomain: "atlasrobotics.io",
  championName: "Maria Hernández",
  championTitle: "Head of RevOps",
  championEmail: "maria@atlasrobotics.io",
  sellerName: "Daniel Reyes",
  sellerTitle: "Account Executive",
  sellerCompany: "Aftercall",
  sellerAvatarUrl: "https://i.pravatar.cc/200?img=12",
  stakeholders: [
    {
      persona: "champion",
      name: "Maria Hernández",
      title: "Head of RevOps",
      email: "maria@atlasrobotics.io",
      headline: "Your shortcut to a green-lit deal",
      pageMarkdown: [
        "## Why this matters for you, Maria",
        "",
        "You told us the slowest part of every deal at Atlas is the internal review with Finance and IT.",
        "Aftercall packages everything those reviewers need into a single link — no more chasing PDFs across email threads.",
        "",
        "**What you can do right now**",
        "- Forward this link to Carlos (CFO) and Priya (IT) — each lands on a page built for them.",
        "- Open the *Mutual Action Plan* tab to see the next three steps we agreed on.",
        "- The ROI calculator below is pre-loaded with Atlas' public financials — edit any input to test the model live.",
      ].join("\n"),
      ctas: [
        { label: "Forward to your team", href: "#forward", variant: "solid" },
        { label: "Book the next call", href: "#calendar", variant: "outline" },
      ],
    },
    {
      persona: "cfo",
      name: "Carlos Mendoza",
      title: "Chief Financial Officer",
      email: "carlos@atlasrobotics.io",
      headline: "The ROI math, in your numbers",
      pageMarkdown: [
        "## ROI summary for Atlas Robotics",
        "",
        "Based on Atlas' FY24 disclosures: **$48M revenue**, **220 employees**, and an estimated **30 seller headcount**, Aftercall expected impact in year one:",
        "",
        "- **+$1.2M new revenue** from 3 pts win-rate improvement on $40M qualified pipeline",
        "- **−$210K cost** from reclaiming 4 hrs/week per AE on deal-room prep",
        "- **Payback in <3 months** at list price",
        "",
        "All assumptions are editable in the ROI tab below. The model uses your inputs — not ours.",
      ].join("\n"),
      ctas: [
        { label: "Download the model", href: "#roi-pdf", variant: "solid" },
        { label: "Security & SOC2", href: "#security", variant: "ghost" },
      ],
    },
    {
      persona: "it",
      name: "Priya Sharma",
      title: "Director of Information Security",
      email: "priya@atlasrobotics.io",
      headline: "How Aftercall fits your stack",
      pageMarkdown: [
        "## Architecture, security & data residency",
        "",
        "- **Deployment**: Single-tenant on AWS us-east-1; EU region available on request.",
        "- **Data residency**: All deal-room artifacts stay in the region you choose. No cross-region replication by default.",
        "- **Auth**: SAML SSO + SCIM provisioning. Magic-link only used for buyer-side stakeholders.",
        "- **Certifications**: SOC 2 Type II (2025), ISO 27001 in flight (audit Q3 2026).",
        "- **Integrations**: Salesforce + HubSpot via OAuth, scoped read-only by default.",
        "",
        "Full architecture diagram and pen-test report linked below.",
      ].join("\n"),
      ctas: [
        { label: "Architecture diagram", href: "#arch", variant: "solid" },
        { label: "SOC 2 report", href: "#soc2", variant: "outline" },
      ],
    },
    {
      persona: "end_user",
      name: "Diego Ortiz",
      title: "Senior Account Executive",
      email: "diego@atlasrobotics.io",
      headline: "What Monday morning looks like",
      pageMarkdown: [
        "## A day with Aftercall, Diego",
        "",
        "After your Friday discovery call, you click one button in Salesforce. By Monday 9am:",
        "",
        "1. Your champion has a personalized link in their inbox — addressed by name, in your voice.",
        "2. Each stakeholder on their committee gets a page built for them, not a generic PDF.",
        "3. Slack pings you the moment any of them open the room or change the ROI inputs.",
        "",
        "No more 'did they get the deck?' guesswork. No more chasing the CFO for two weeks.",
      ].join("\n"),
      ctas: [
        { label: "Watch the 90-sec tour", href: "#tour", variant: "solid" },
      ],
    },
  ],
  voiceIntro: {
    script:
      "Hi Maria, Daniel here from Aftercall. Thanks for the call on Friday — really enjoyed digging into what's slowing down your deal reviews. I put together this short room for you and the team. The CFO tab has the ROI math in Atlas' own numbers, and Priya should head straight to the IT tab. Anything missing, just hit reply. Talk soon.",
    audioUrl: null,
    voiceId: "placeholder-voice-id",
    durationSec: 38,
  },
  roiInputs: {
    currency: "USD",
    annualRevenue: 48_000_000,
    headcount: 220,
    assumedSavingsPct: 0.05,
    hoursSavedPerRepPerWeek: 4,
    avgFullyLoadedHourlyRate: 95,
  },
  mutualActionPlan: [
    { step: "Share this room with Carlos (CFO) and Priya (IT)", owner: "buyer", dueDate: "2026-05-27", done: false },
    { step: "Security review call — 30 min with Priya", owner: "shared", dueDate: "2026-05-30", done: false },
    { step: "ROI deep-dive with Carlos using Atlas FY24 data", owner: "shared", dueDate: "2026-06-03", done: false },
    { step: "Procurement & MSA red-line", owner: "buyer", dueDate: "2026-06-10", done: false },
    { step: "Mutual signing — target close", owner: "shared", dueDate: "2026-06-17", done: false },
  ],
  createdAt: new Date().toISOString(),
};
